name: Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...

      - name: Build
        env:
          GOOS: ${{ matrix.os == 'windows-latest' && 'windows' || matrix.os == 'macos-latest' && 'darwin' || 'linux' }}
          GOARCH: amd64
        run: go build -v -o cpp2py ./cmd/cpp2py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cpp2py-${{ matrix.os }}
          path: cpp2py

  create-release:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: cpp2py-*

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/cpp2py-ubuntu-latest
            artifacts/cpp2py-windows-latest
            artifacts/cpp2py-macos-latest
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}